### ISSUE TITLE
Airship Level Problems

### ISSUE THREAD

**Issue by Chickensaver** [RoadrunnerWMC/Reggie-Next#13]
I've been using ReggieNext for a while now and I can't seem to open any airship files or place down rotating flame jet cannons and nut platforms.  The problem seems to be in the file sprites.pyc on line 4965.  I assume that the extra O in newOoffsetRight shouldn't be there but I have no idea how to open the file to fix this.  What makes it worse, is that I am running a windows computer, not a linux so it may be difficult for you to help me fix this.  If I am completely wrong about the error and something else is causing this mishap, please let me know so I can open airship levels and so I can use rotating flame jets.  Thanks!

HERE IS THE EXACT ERROR:
Traceback (most recent call last):
  File "reggie.py", line 15127, in <module>
  File "reggie.py", line 15100, in main
  File "reggie.py", line 11998, in __init2__
  File "reggie.py", line 13557, in HandleSpriteImages
  File "reggie.py", line 3303, in InitialiseSprite
  File "reggie.py", line 3315, in UpdateDynamicSizing
  File "sprites.pyc", line 4965, in SizeNutPlatform
NameError: global name 'newOoffsetRight' is not defined

HERE IS THE OTHER EXACT ERROR:
Traceback (most recent call last):
  File "reggie.py", line 7420, in mousePressEvent
  File "reggie.py", line 3153, in __init__
  File "reggie.py", line 3294, in InitialiseSprite
  File "sprites.pyc", line 2480, in InitRotFlameCannon
  File "sprites.pyc", line 6097, in LoadRotFlameCannon
AttributeError: 'NoneType' object has no attribute 'mirrored'

**Comment by RoadrunnerWMC** [comment]
Yeah, it would need to be recompiled to fix those bugs, which would be kind of hard for me to do. I can update the code anyway, though.

You might want to try [the original Reggie editor](http://rvlution.net/reggie/) when editing those levels. It has fewer features, but is extremely stable.

**Comment by Chickensaver** [comment]
Thanks!  I never thought about using the original editor!  I'll do that for my airship levels!

**Comment by RoadrunnerWMC** [comment]
It actually looks like those errors correspond to an older version of RN than the one in this repo. I guess there's nothing to fix, then...

**Comment by Chickensaver** [comment]
Hmm.  I guess I'll just redownload then.  I didn't realize I was using an older version of ReggieNext.  Thanks for notifying me.
