### ISSUE TITLE
Help with the below

### ISSUE THREAD

**Issue by lunathir** [RoadrunnerWMC/Reggie-Next#9]
I get an error which is below:
`Traceback (most recent call last):
  File "reggie.py", line 74, in <module>
    import LHTool
ModuleNotFoundError: No module named 'sarc'`
I'm not very good with Python, so that's one reason I asked.

**Comment by RoadrunnerWMC** [comment]
I fixed it; please redownload and try again.

**Comment by cratty79** [comment]
I have yet again broken it:
`Traceback (most recent call last):
  File "C:\Users\007\Desktop\Reggie-Next-master\reggie.py", line 21563, in <module>
    generateStringsXML = True
  File "C:\Users\007\Desktop\Reggie-Next-master\reggie.py", line 21551, in main
  File "C:\Users\007\Desktop\Reggie-Next-master\reggie.py", line 17086, in __init__
TypeError: connect() failed between timeout() and Autosave()`
Also, how do you switch to NSMB2 mode?
